name: serinus_serve_static
description: "A Serinus Plugin to serve static files in a Serinus Application"
version: 1.0.2
repository: https://github.com/serinus-nest/serve_static
homepage: https://github.com/serinus-nest
documentation: https://docs.serinus.app/plugins/serve_static
tag: 
  - server
  - static
  - backend
  - web
  - http


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serinus: ^0.5.0
  
